### PR TITLE
Added global chat, fix #69, and fixed mentioning in threads

### PR DESCRIPTION
**Pull request by DWAA1660**

### CODE REVIEW

**Comment by DWAA1660** [comment]
hows this look

**Comment by srnyx** [comment]
Please improve commit messages for the future. @Chrizxz and I were discussing it a while ago and we both decided to have cleaner ones.

**Comment by DWAA1660** [comment]
> Please improve commit messages for the future. @Chrizxz and I were discussing it a while ago and we both decided to have cleaner ones. It's mainly just ones like:
> 
> * `MORE CODACY IM ON A ROLL`
> * `Final codacy`
> * `LAST ONE I PROMISE`

image
literally was doing what you do

**Comment by srnyx** [comment]
> literally was doing what you do

That was before @Chrizxz and I discussed commit messages. And Cobalt is a much more collaborative project than Vanadium, so it's much more important to use correct commit messages here than there.

**Comment by Chrizxz** [comment]
> > literally was doing what you do
> 
> That was before @Chrizxz and I discussed commit messages. And Cobalt is a much more collaborative project than Vanadium, so it's much more important to use correct commit messages here than there. It's all good though, just remember for future reference.

I'll remember urmom for future reference

**Comment by DWAA1660** [comment]
> > literally was doing what you do
> 
> That was before @Chrizxz and I discussed commit messages. And Cobalt is a much more collaborative project than Vanadium, so it's much more important to use correct commit messages here than there. It's all good though, just remember for future reference.

I'm literally the only one who committed since terroid remade

**Comment by DWAA1660** [comment]
finished #61 #9 is done i think that's only ones

**Pull request merged**
